### ISSUE TITLE
Category does not exist error

### ISSUE THREAD

**Issue by HannesMorre** [sparkmicro/Ki-nTree#178]
I get this error when trying to use the category "Miscellaneous", but this category clearly does exist in inventree. I also reloaded inventree categories in Ki-nTree v1.0.3.

`[ERROR]    Category (['Miscellaneous']) does not exist in InvenTree`
![image](https://github.com/sparkmicro/Ki-nTree/assets/71696745/47a2b47c-0fa5-4e77-8784-c5dee3075702)

**Comment by HannesMorre** [comment]
All other categories are fine btw. I pulled a list of all categories with an API call on our inventree server and te "miscellaneous" category is present and anothing looks out of the ordinary.

**Comment by Thieuzor** [comment]
I'm experiencing the same issue when creating a new part in the 'miscellaneous' category:
![image](https://github.com/sparkmicro/Ki-nTree/assets/49872441/73b97b01-ae8d-44c2-89b3-d91d0bdb2c1f)

Same version information as above.
The category exists in Inventree:
![image](https://github.com/sparkmicro/Ki-nTree/assets/49872441/52baa8ef-b3ec-4105-b620-76a78efbb551)

**Comment by eeintech** [comment]
Hello @HannesMorre @Thieuzor I am really confused because I don't have any issue with the `Miscellaneous` category using Ki-nTree v1.0.3 and InvenTree v0.12.7. I repeated it a couple of times with the `1490-NRF5340-DK-ND` part and got only good results:

``` shell
[MAIN]  Using Digi-Key cached data for 1490-NRF5340-DK-ND
[TREE]  Successfully connected to InvenTree server (ENV=DEVELOPMENT)
[INFO]  Warning: Parameter map for "Miscellaneous" does not exist or is empty
[INFO]  Success: Added new part to InvenTree
[INFO]  Warning: Image download failed (HTTP Error)

[MAIN]  Creating manufacturer part
[INFO]  Success: Added new manufacturer part

[MAIN]  Creating supplier part
[INFO]  Success: Added new supplier part

[MAIN]  Processing Price Breaks
[INFO]  Success: The price breaks were updated
```

I deleted the category and re-added it and it is still working fine... not sure how to reproduce this one 😬 

I might sounds stupid but have you checked for whitespace in the name on InvenTree GUI?

![image](https://github.com/sparkmicro/Ki-nTree/assets/4020546/34e4b800-919e-40d9-9899-4e25e836e041)

**Comment by HannesMorre** [comment]
Good thinking, but no whitespace to be found in the name. Is it possible that we experience problems because Inventree is running in a docker?

![image](https://github.com/sparkmicro/Ki-nTree/assets/71696745/ef9f835e-5c1a-4864-9a48-6c1592744ad9)

**Comment by eeintech** [comment]
I don't think Docker is the problem, because other categories are working for you. I find it extremely strange that you are two users experiencing the same issue but with the same setup I'm not able to... Have you tried Ki-nTree `1.0.4` which I released yesterday? There is a very low chance it fixes it, somehow, some way...

**Comment by HannesMorre** [comment]
We tried with 1.0.4 but still the same issue. We added a subcategory to the miscellaneous category and when we create articles in this category, there are no issues.

**Comment by eeintech** [comment]
> We added a subcategory to the miscellaneous category and when we create articles in this category, there are no issues.

That's good news, I also had a subcategory in Miscellaneous early on my testing and deleted it because I thought it could be the reason why it was working but it wasn't... I really have no clue how to help you further though 🤔

**Comment by HannesMorre** [comment]
We'll work with subcategories for now. Thanks anyway for trying to help us 😄
